version: "3.9"
services:
  trading-bot:
    build: .
    container_name: ai_trading_bot
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ../config/secrets.env
    volumes:
      - ../logs:/app/logs
